volumes:
  bundler:
    driver: local
  go_pkg:
    driver: local
  pnpm:
    driver: local
  main_db:
    driver: local
  auth_db:
    driver: local
services:
  front:
    build:
      context: ./apps/front
      # frontディレクトリからの相対パス
      dockerfile: ../../docker/front/Dockerfile
    volumes:
      - ./apps/front:/app
      - pnpm:/app/.pnpm-store
    command: ["pnpm", "run", "dev"]
    ports:
      - 3000:3000
  api-main:
    build:
      context: ./apps/api/main
      # api/mainディレクトリからの相対パス
      dockerfile: ../../../docker/api/main/Dockerfile
    volumes:
      - ./apps/api/main:/app
      - bundler:/app/vendor/bundle
    ports:
      - 4000:3000
    env_file:
      - env_files/api.main.env
  api-auth:
    build:
      context: ./apps/api/auth
      # api/authディレクトリからの相対パス
      dockerfile: ../../../docker/api/auth/Dockerfile
    volumes:
      - ./apps/api/auth:/app
      - go_pkg:/go/pkg/mod
    ports:
      - 8080:8080
    env_file:
      - env_files/api.auth.env
    environment:
      GOPRIVATE: "github.com/kohTkd/*"
      CGO_ENABLED: 0
  database-auth:
    build:
      context: ./databases/auth
      dockerfile: ../../docker/databases/auth/Dockerfile
    volumes:
      - auth_db:/var/lib/mysql
    env_file:
      - env_files/api.auth.env
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 13306:3306
  database-main:
    build:
      context: ./databases/main
      dockerfile: ../../docker/databases/main/Dockerfile
    volumes:
      - main_db:/var/lib/postgresql/data
    env_file:
      - env_files/api.main.env
    ports:
      - 15432:5432
