version: "3.8"
volumes:
  bundler:
    driver: local
  pnpm:
    driver: local
  main_db:
    driver: local
  auth_db:
    driver: local
services:
  api-main:
    build:
      context: ./apps/api/main
      # api/mainディレクトリからの相対パス
      dockerfile: ../../../docker/api/main/Dockerfile
    volumes:
      - ./apps/api/main:/app
      - bundler:/app/vendor/bundle
    ports:
      - 5000:3000
    env_file:
      - env_files/api.main.env
  front:
    build:
      context: ./apps/front
      # frontディレクトリからの相対パス
      dockerfile: ../../docker/front/Dockerfile
    volumes:
      - ./apps/front:/app
      - pnpm:/app/.pnpm-store
    command: ["pnpm", "run", "dev"]
    ports:
      - 3000:3000
  database-main:
    build:
      context: ./databases/main
      dockerfile: ../../docker/databases/main/Dockerfile
    volumes:
      - main_db:/var/lib/postgresql/data
    env_file:
      - env_files/api.main.env
