version: "3.8"
services:
  api-main-dev:
    image: experimental_learning-api-main
    volumes:
      - ./apps/api/main:/app
      - bundler:/app/vendor/bundle
      - ./apps/api/main/.rubocop.yml:/root/.rubocop.yml
      - ./apps/api/main/.solargraph.yml:/root/.config/solargraph/config.yml
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658
    ports:
      - 7658:7658
  protoc:
    build:
      context: ./docker/tools/protoc
    platform: linux/amd64
    volumes:
      - ./docker/tools/protobuf/protoc.sh:/usr/local/bin/protoc.sh
      - ./apps/api/auth/api:/src/auth
      - ./apps/api/auth/internal/adapter/grpc:/dist/server/auth/go
      - ./apps/api/main/lib/grpc:/dist/client/ruby
