version: "3.8"
services:
  api-dev:
    image: aws_experiments-api
    volumes:
      - ./apps/api:/app
      - bundler:/app/vendor/bundle
      - ./apps/api/.rubocop.yml:/root/.rubocop.yml
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658
    ports:
      - 7658:7658
