#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $API_DB_USER WITH LOGIN PASSWORD '$API_DB_PASSWORD';
    ALTER ROLE $API_DB_USER with SUPERUSER;
    CREATE DATABASE $API_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $API_DB_NAME TO $API_DB_USER;
    ALTER DATABASE $API_DB_NAME SET TIMEZONE = 'Asia/Tokyo';

    CREATE DATABASE $TEST_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $TEST_DB_NAME TO $API_DB_USER;
    ALTER DATABASE $TEST_DB_NAME SET TIMEZONE = 'Asia/Tokyo';
EOSQL
