#!/bin/bash
set -e

echo 'Initialization start.'

echo 'Creating users'
mysql -u "$MYSQL_ROOT_USER" -p${MYSQL_ROOT_PASSWORD} <<-EOSQL
    CREATE USER '$DB_READ_USER' IDENTIFIED BY '$DB_READ_PASSWORD';
    CREATE USER '$DB_WRITE_USER' IDENTIFIED BY '$DB_WRITE_PASSWORD';

    CREATE DATABASE $DB_NAME;
    CREATE DATABASE $TEST_DB_NAME;

    GRANT SELECT ON $DB_NAME.* TO $DB_READ_USER;
    GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_WRITE_USER;
    GRANT SELECT ON $TEST_DB_NAME.* TO $DB_READ_USER;
    GRANT ALL PRIVILEGES ON $TEST_DB_NAME.* TO $DB_WRITE_USER;
EOSQL

echo 'Initialization finished'
